"""update oauth account model fields

Revision ID: bdb140899b43
Revises: be2fb149d8a5
Create Date: 2025-06-06 02:26:48.354926

"""
import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # pyright: ignore  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence  # pyright: ignore

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID # pyright: ignore
sa.DateTimeUTC = DateTimeUTC  # pyright: ignore
sa.ORA_JSONB = ORA_JSONB  # pyright: ignore
sa.EncryptedString = EncryptedString  # pyright: ignore
sa.EncryptedText = EncryptedText  # pyright: ignore
sa.StoredObject = StoredObject  # pyright: ignore
sa.PasswordHash = PasswordHash  # pyright: ignore

# revision identifiers, used by Alembic.
revision = 'bdb140899b43'
down_revision = 'be2fb149d8a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('provider_user_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_oauth_provider_oauth_id', ['oauth_name', 'account_id'], unique=False)
        batch_op.create_index('ix_oauth_user_provider', ['user_id', 'oauth_name'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.drop_index('ix_oauth_user_provider')
        batch_op.drop_index('ix_oauth_provider_oauth_id')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('provider_user_data')
        batch_op.drop_column('scope')
        batch_op.drop_column('token_expires_at')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
