// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as ClientOptions, type TDataShape, urlSearchParamsBodySerializer } from "@hey-api/client-axios"
import { client as _heyApiClient } from "./client.gen"
import type {
  AcceptTeamInvitationData,
  AcceptTeamInvitationError,
  AcceptTeamInvitationResponse,
  AccountDeleteData,
  AccountDeleteResponse,
  AccountLoginData,
  AccountLoginError,
  AccountLoginResponse,
  AccountLogoutData,
  AccountLogoutResponse,
  AccountPasswordUpdateData,
  AccountPasswordUpdateError,
  AccountPasswordUpdateResponse,
  AccountProfileData,
  AccountProfileResponse,
  AccountProfileUpdateData,
  AccountProfileUpdateError,
  AccountProfileUpdateResponse,
  AccountRegisterData,
  AccountRegisterError,
  AccountRegisterResponse,
  AddMemberToTeamData,
  AddMemberToTeamError,
  AddMemberToTeamResponse,
  ApiAuthOauthAccountsGetOauthAccountsData,
  ApiAuthOauthAccountsGetOauthAccountsError,
  ApiAuthOauthAccountsGetOauthAccountsResponse,
  ApiAuthOauthGoogleCallbackGoogleCallbackData,
  ApiAuthOauthGoogleCallbackGoogleCallbackError,
  ApiAuthOauthGoogleCallbackGoogleCallbackResponse,
  ApiAuthOauthGoogleGoogleAuthorizeData,
  ApiAuthOauthGoogleGoogleAuthorizeError,
  ApiAuthOauthGoogleGoogleAuthorizeResponse,
  ApiAuthOauthLinkLinkOauthAccountData,
  ApiAuthOauthLinkLinkOauthAccountError,
  ApiAuthOauthLinkLinkOauthAccountResponse,
  ApiAuthOauthUnlinkUnlinkOauthAccountData,
  ApiAuthOauthUnlinkUnlinkOauthAccountError,
  ApiAuthOauthUnlinkUnlinkOauthAccountResponse,
  ApiEmailVerificationRequestRequestVerificationData,
  ApiEmailVerificationRequestRequestVerificationError,
  ApiEmailVerificationRequestRequestVerificationResponse,
  ApiEmailVerificationStatusUserIdGetVerificationStatusData,
  ApiEmailVerificationStatusUserIdGetVerificationStatusError,
  ApiEmailVerificationStatusUserIdGetVerificationStatusResponse,
  ApiEmailVerificationVerifyVerifyEmailData,
  ApiEmailVerificationVerifyVerifyEmailError,
  ApiEmailVerificationVerifyVerifyEmailResponse,
  AssignUserRoleData,
  AssignUserRoleError,
  AssignUserRoleResponse,
  CreateRoleData,
  CreateRoleError,
  CreateRoleResponse,
  CreateTagData,
  CreateTagError,
  CreateTagResponse,
  CreateTeamData,
  CreateTeamError,
  CreateTeamInvitationData,
  CreateTeamInvitationError,
  CreateTeamInvitationResponse,
  CreateTeamResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteRoleData,
  DeleteRoleError,
  DeleteRoleResponse,
  DeleteTagData,
  DeleteTagError,
  DeleteTagResponse,
  DeleteTeamData,
  DeleteTeamError,
  DeleteTeamInvitationData,
  DeleteTeamInvitationError,
  DeleteTeamInvitationResponse,
  DeleteTeamResponse,
  DeleteUserData,
  DeleteUserError,
  DeleteUserResponse,
  ForgotPasswordData,
  ForgotPasswordError,
  ForgotPasswordResponse2,
  GetRoleData,
  GetRoleError,
  GetRoleResponse,
  GetTagData,
  GetTagError,
  GetTagResponse,
  GetTeamData,
  GetTeamError,
  GetTeamResponse,
  GetUserData,
  GetUserError,
  GetUserResponse,
  ListRolesData,
  ListRolesError,
  ListRolesResponse,
  ListTagsData,
  ListTagsError,
  ListTagsResponse,
  ListTeamInvitationsData,
  ListTeamInvitationsError,
  ListTeamInvitationsResponse,
  ListTeamsData,
  ListTeamsError,
  ListTeamsResponse,
  ListUsersData,
  ListUsersError,
  ListUsersResponse,
  RemoveMemberFromTeamData,
  RemoveMemberFromTeamError,
  RemoveMemberFromTeamResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse2,
  RevokeUserRoleData,
  RevokeUserRoleError,
  RevokeUserRoleResponse,
  SystemHealthData,
  SystemHealthResponse,
  UpdateRoleData,
  UpdateRoleError,
  UpdateRoleResponse,
  UpdateTagData,
  UpdateTagError,
  UpdateTagResponse,
  UpdateTeamData,
  UpdateTeamError,
  UpdateTeamResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  ValidateResetTokenData,
  ValidateResetTokenError,
  ValidateResetTokenResponse2,
} from "./types.gen"

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Health Check
 */
export const systemHealth = <ThrowOnError extends boolean = false>(options?: Options<SystemHealthData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<SystemHealthResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/health",
    ...options,
  })
}

/**
 * ForgotPassword
 */
export const forgotPassword = <ThrowOnError extends boolean = false>(options: Options<ForgotPasswordData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<ForgotPasswordResponse2, ForgotPasswordError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/access/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * Login
 */
export const accountLogin = <ThrowOnError extends boolean = false>(options: Options<AccountLoginData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<AccountLoginResponse, AccountLoginError, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/access/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
  })
}

/**
 * Logout
 */
export const accountLogout = <ThrowOnError extends boolean = false>(options?: Options<AccountLogoutData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).post<AccountLogoutResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/access/logout",
    ...options,
  })
}

/**
 * ValidateResetToken
 */
export const validateResetToken = <ThrowOnError extends boolean = false>(options: Options<ValidateResetTokenData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ValidateResetTokenResponse2, ValidateResetTokenError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/access/reset-password",
    ...options,
  })
}

/**
 * ResetPasswordWithToken
 */
export const resetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<ResetPasswordResponse2, ResetPasswordError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/access/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * Signup
 */
export const accountRegister = <ThrowOnError extends boolean = false>(options: Options<AccountRegisterData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<AccountRegisterResponse, AccountRegisterError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/access/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * GetVerificationStatus
 */
export const apiEmailVerificationStatusUserIdGetVerificationStatus = <ThrowOnError extends boolean = false>(
  options: Options<ApiEmailVerificationStatusUserIdGetVerificationStatusData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ApiEmailVerificationStatusUserIdGetVerificationStatusResponse,
    ApiEmailVerificationStatusUserIdGetVerificationStatusError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/email-verification/status/{user_id}",
    ...options,
  })
}

/**
 * RequestVerification
 */
export const apiEmailVerificationRequestRequestVerification = <ThrowOnError extends boolean = false>(
  options: Options<ApiEmailVerificationRequestRequestVerificationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<ApiEmailVerificationRequestRequestVerificationResponse, ApiEmailVerificationRequestRequestVerificationError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/email-verification/request",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * VerifyEmail
 */
export const apiEmailVerificationVerifyVerifyEmail = <ThrowOnError extends boolean = false>(options: Options<ApiEmailVerificationVerifyVerifyEmailData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<ApiEmailVerificationVerifyVerifyEmailResponse, ApiEmailVerificationVerifyVerifyEmailError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/email-verification/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * GetOauthAccounts
 */
export const apiAuthOauthAccountsGetOauthAccounts = <ThrowOnError extends boolean = false>(options: Options<ApiAuthOauthAccountsGetOauthAccountsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ApiAuthOauthAccountsGetOauthAccountsResponse, ApiAuthOauthAccountsGetOauthAccountsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/auth/oauth/accounts",
    ...options,
  })
}

/**
 * GoogleAuthorize
 */
export const apiAuthOauthGoogleGoogleAuthorize = <ThrowOnError extends boolean = false>(options: Options<ApiAuthOauthGoogleGoogleAuthorizeData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ApiAuthOauthGoogleGoogleAuthorizeResponse, ApiAuthOauthGoogleGoogleAuthorizeError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/auth/oauth/google",
    ...options,
  })
}

/**
 * GoogleCallback
 */
export const apiAuthOauthGoogleCallbackGoogleCallback = <ThrowOnError extends boolean = false>(options: Options<ApiAuthOauthGoogleCallbackGoogleCallbackData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ApiAuthOauthGoogleCallbackGoogleCallbackResponse, ApiAuthOauthGoogleCallbackGoogleCallbackError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/auth/oauth/google/callback",
    ...options,
  })
}

/**
 * LinkOauthAccount
 */
export const apiAuthOauthLinkLinkOauthAccount = <ThrowOnError extends boolean = false>(options: Options<ApiAuthOauthLinkLinkOauthAccountData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<ApiAuthOauthLinkLinkOauthAccountResponse, ApiAuthOauthLinkLinkOauthAccountError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/auth/oauth/link",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * UnlinkOauthAccount
 */
export const apiAuthOauthUnlinkUnlinkOauthAccount = <ThrowOnError extends boolean = false>(options: Options<ApiAuthOauthUnlinkUnlinkOauthAccountData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<ApiAuthOauthUnlinkUnlinkOauthAccountResponse, ApiAuthOauthUnlinkUnlinkOauthAccountError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/auth/oauth/unlink",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * User Profile
 * User profile information.
 */
export const accountProfile = <ThrowOnError extends boolean = false>(options?: Options<AccountProfileData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<AccountProfileResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/me",
    ...options,
  })
}

/**
 * UpdateProfile
 */
export const accountProfileUpdate = <ThrowOnError extends boolean = false>(options: Options<AccountProfileUpdateData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<AccountProfileUpdateResponse, AccountProfileUpdateError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * RemoveAccount
 */
export const accountDelete = <ThrowOnError extends boolean = false>(options?: Options<AccountDeleteData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).delete<AccountDeleteResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/profile",
    ...options,
  })
}

/**
 * UpdatePassword
 */
export const accountPasswordUpdate = <ThrowOnError extends boolean = false>(options: Options<AccountPasswordUpdateData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<AccountPasswordUpdateResponse, AccountPasswordUpdateError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * DeleteRole
 */
export const deleteRole = <ThrowOnError extends boolean = false>(options: Options<DeleteRoleData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteRoleResponse, DeleteRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/roles/{role_id}",
    ...options,
  })
}

/**
 * GetRole
 */
export const getRole = <ThrowOnError extends boolean = false>(options: Options<GetRoleData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetRoleResponse, GetRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/roles/{role_id}",
    ...options,
  })
}

/**
 * UpdateRole
 */
export const updateRole = <ThrowOnError extends boolean = false>(options: Options<UpdateRoleData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<UpdateRoleResponse, UpdateRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/roles/{role_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * CreateRole
 */
export const createRole = <ThrowOnError extends boolean = false>(options: Options<CreateRoleData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateRoleResponse, CreateRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/roles/{role_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * ListRoles
 */
export const listRoles = <ThrowOnError extends boolean = false>(options?: Options<ListRolesData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<ListRolesResponse, ListRolesError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/roles",
    ...options,
  })
}

/**
 * ListUsers
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<ListUsersResponse, ListUsersError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users",
    ...options,
  })
}

/**
 * CreateUser
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateUserResponse, CreateUserError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * DeleteUser
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteUserResponse, DeleteUserError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users/{user_id}",
    ...options,
  })
}

/**
 * GetUser
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetUserResponse, GetUserError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users/{user_id}",
    ...options,
  })
}

/**
 * UpdateUser
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<UpdateUserResponse, UpdateUserError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * ListTeams
 */
export const listTeams = <ThrowOnError extends boolean = false>(options?: Options<ListTeamsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<ListTeamsResponse, ListTeamsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams",
    ...options,
  })
}

/**
 * CreateTeam
 */
export const createTeam = <ThrowOnError extends boolean = false>(options: Options<CreateTeamData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateTeamResponse, CreateTeamError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * DeleteTeam
 */
export const deleteTeam = <ThrowOnError extends boolean = false>(options: Options<DeleteTeamData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteTeamResponse, DeleteTeamError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams/{team_id}",
    ...options,
  })
}

/**
 * GetTeam
 */
export const getTeam = <ThrowOnError extends boolean = false>(options: Options<GetTeamData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetTeamResponse, GetTeamError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams/{team_id}",
    ...options,
  })
}

/**
 * UpdateTeam
 */
export const updateTeam = <ThrowOnError extends boolean = false>(options: Options<UpdateTeamData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<UpdateTeamResponse, UpdateTeamError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams/{team_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * DeleteTeamInvitation
 */
export const deleteTeamInvitation = <ThrowOnError extends boolean = false>(options: Options<DeleteTeamInvitationData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteTeamInvitationResponse, DeleteTeamInvitationError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/{team_id}/{invitation_id}",
    ...options,
  })
}

/**
 * AcceptTeamInvitation
 */
export const acceptTeamInvitation = <ThrowOnError extends boolean = false>(options: Options<AcceptTeamInvitationData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<AcceptTeamInvitationResponse, AcceptTeamInvitationError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/{team_id}/{invitation_id}",
    ...options,
  })
}

/**
 * ListTeamInvitations
 */
export const listTeamInvitations = <ThrowOnError extends boolean = false>(options: Options<ListTeamInvitationsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ListTeamInvitationsResponse, ListTeamInvitationsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/{team_id}",
    ...options,
  })
}

/**
 * CreateTeamInvitation
 */
export const createTeamInvitation = <ThrowOnError extends boolean = false>(options: Options<CreateTeamInvitationData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateTeamInvitationResponse, CreateTeamInvitationError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/{team_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * RevokeRole
 */
export const revokeUserRole = <ThrowOnError extends boolean = false>(options: Options<RevokeUserRoleData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<RevokeUserRoleResponse, RevokeUserRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * AssignRole
 */
export const assignUserRole = <ThrowOnError extends boolean = false>(options: Options<AssignUserRoleData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<AssignUserRoleResponse, AssignUserRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/users/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * RemoveMemberFromTeam
 */
export const removeMemberFromTeam = <ThrowOnError extends boolean = false>(options: Options<RemoveMemberFromTeamData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<RemoveMemberFromTeamResponse, RemoveMemberFromTeamError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams/{team_id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * AddMemberToTeam
 */
export const addMemberToTeam = <ThrowOnError extends boolean = false>(options: Options<AddMemberToTeamData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<AddMemberToTeamResponse, AddMemberToTeamError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/teams/{team_id}/members",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * DeleteTag
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteTagResponse, DeleteTagError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/tags/{tag_id}",
    ...options,
  })
}

/**
 * GetTag
 */
export const getTag = <ThrowOnError extends boolean = false>(options: Options<GetTagData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetTagResponse, GetTagError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/tags/{tag_id}",
    ...options,
  })
}

/**
 * UpdateTag
 */
export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<UpdateTagResponse, UpdateTagError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/tags/{tag_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * CreateTag
 */
export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateTagResponse, CreateTagError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/tags/{tag_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
}

/**
 * ListTags
 */
export const listTags = <ThrowOnError extends boolean = false>(options?: Options<ListTagsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<ListTagsResponse, ListTagsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/tags",
    ...options,
  })
}
