// This file is auto-generated by @hey-api/openapi-ts

export type AccountLogin = {
    username: string;
    password: string;
};

export type AccountRegister = {
    email: string;
    password: string;
    name?: string | null;
    username?: string | null;
    initialTeamName?: string | null;
};

export type AppSettings = {
    NAME?: string;
    VERSION?: string;
    CONTACT_NAME?: string;
    CONTACT_EMAIL?: string;
    URL?: string;
    DEBUG?: boolean;
    SECRET_KEY?: string;
    JWT_ENCRYPTION_ALGORITHM?: string;
    ALLOWED_CORS_ORIGINS?: Array<string> | string;
    CSRF_COOKIE_NAME?: string;
    CSRF_HEADER_NAME?: string;
    CSRF_COOKIE_SECURE?: boolean;
    STATIC_DIR?: string;
    STATIC_URL?: string;
    BASE_URL?: string | null;
    DEV_MODE?: boolean;
    ENABLE_INSTRUMENTATION?: boolean;
    GOOGLE_OAUTH2_CLIENT_ID?: string;
    GOOGLE_OAUTH2_CLIENT_SECRET?: string;
    ENV_SECRETS?: string;
};

export type EmailVerificationConfirm = {
    token: string;
};

export type EmailVerificationRequest = {
    email: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ForgotPasswordResponse = {
    message: string;
    expires_in_minutes?: number;
};

export type Message = {
    message: string;
};

export type OAuth2Login = {
    access_token: string;
    token_type: string;
    refresh_token?: string | null;
    expires_in?: number | null;
};

export type OAuthAccountInfo = {
    provider: string;
    oauth_id: string;
    email: string;
    linked_at: string;
    name?: string | null;
    avatar_url?: string | null;
    last_login_at?: string | null;
};

export type OAuthAuthorizationResponse = {
    authorization_url: string;
    state?: string | null;
};

export type OAuthLinkRequest = {
    provider: 'google';
};

export type OauthAccount = {
    id: string;
    oauthName: string;
    accessToken: string;
    accountId: string;
    accountEmail: string;
    expiresAt?: number | null;
    refreshToken?: string | null;
};

export type PasswordUpdate = {
    currentPassword: string;
    newPassword: string;
};

export type ProfileUpdate = {
    name?: string | null;
    username?: string | null;
    phone?: string | null;
};

export type ResetPasswordRequest = {
    token: string;
    password: string;
    password_confirm: string;
};

export type ResetPasswordResponse = {
    message: string;
    user_id: string;
};

export type Role = {
    id: string;
    slug: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type RoleCreate = {
    name: string;
};

export type RoleUpdate = {
    name?: string | null;
};

export type SystemHealth = {
    databaseStatus?: 'online' | 'offline';
    app?: string;
    version?: string;
};

export type Tag = {
    id: string;
    slug: string;
    name: string;
};

export type TagCreate = {
    name: string;
};

export type TagUpdate = {
    name?: string | null;
};

export type Team = {
    id: string;
    name: string;
    description?: string | null;
    members?: Array<TeamMember>;
    tags?: Array<TeamTag>;
};

export type TeamCreate = {
    name: string;
    description?: string | null;
    tags?: Array<string>;
};

export type TeamInvitation = {
    id: string;
    email: string;
    role: TeamRoles;
    createdAt: string;
    updatedAt: string;
};

export type TeamInvitationCreate = {
    email: string;
    role: TeamRoles;
};

export type TeamMember = {
    id: string;
    userId: string;
    email: string;
    name?: string | null;
    role?: TeamRoles | null;
    isOwner?: boolean | null;
};

export type TeamMemberModify = {
    userName: string;
};

/**
 * Valid Values for Team Roles.
 */
export type TeamRoles = 'ADMIN' | 'MEMBER';

export type TeamTag = {
    id: string;
    slug: string;
    name: string;
};

export type TeamUpdate = {
    name?: string | null;
    description?: string | null;
    tags?: Array<string> | null;
};

export type User = {
    id: string;
    email: string;
    name?: string | null;
    username?: string | null;
    phone?: string | null;
    isSuperuser?: boolean;
    isActive?: boolean;
    isVerified?: boolean;
    hasPassword?: boolean;
    teams?: Array<UserTeam>;
    roles?: Array<UserRole>;
    oauthAccounts?: Array<OauthAccount>;
    avatarUrl?: string | null;
};

export type UserCreate = {
    email: string;
    password: string;
    name?: string | null;
    username?: string | null;
    phone?: string | null;
    isSuperuser?: boolean;
    isActive?: boolean;
    isVerified?: boolean;
};

export type UserRole = {
    roleId: string;
    roleSlug: string;
    roleName: string;
    assignedAt: string;
};

export type UserRoleAdd = {
    userName: string;
};

export type UserRoleRevoke = {
    userName: string;
};

export type UserTeam = {
    teamId: string;
    teamName: string;
    isOwner?: boolean;
    role?: TeamRoles;
};

export type UserUpdate = {
    email?: string | null;
    password?: string | null;
    name?: string | null;
    username?: string | null;
    phone?: string | null;
    isSuperuser?: boolean | null;
    isActive?: boolean | null;
    isVerified?: boolean | null;
};

export type ValidateResetTokenResponse = {
    valid: boolean;
    user_id?: string | null;
    expires_at?: string | null;
};

export type SystemHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type SystemHealthResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: SystemHealth;
};

export type SystemHealthResponse = SystemHealthResponses[keyof SystemHealthResponses];

export type ForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/access/forgot-password';
};

export type ForgotPasswordErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ForgotPasswordError = ForgotPasswordErrors[keyof ForgotPasswordErrors];

export type ForgotPasswordResponses = {
    /**
     * Document created, URL follows
     */
    201: ForgotPasswordResponse;
};

export type ForgotPasswordResponse2 = ForgotPasswordResponses[keyof ForgotPasswordResponses];

export type AccountLoginData = {
    body: AccountLogin;
    path?: never;
    query?: never;
    url: '/api/access/login';
};

export type AccountLoginErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AccountLoginError = AccountLoginErrors[keyof AccountLoginErrors];

export type AccountLoginResponses = {
    /**
     * Document created, URL follows
     */
    201: OAuth2Login;
};

export type AccountLoginResponse = AccountLoginResponses[keyof AccountLoginResponses];

export type AccountLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/access/logout';
};

export type AccountLogoutResponses = {
    /**
     * Document created, URL follows
     */
    201: Message;
};

export type AccountLogoutResponse = AccountLogoutResponses[keyof AccountLogoutResponses];

export type ValidateResetTokenData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/api/access/reset-password';
};

export type ValidateResetTokenErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ValidateResetTokenError = ValidateResetTokenErrors[keyof ValidateResetTokenErrors];

export type ValidateResetTokenResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ValidateResetTokenResponse;
};

export type ValidateResetTokenResponse2 = ValidateResetTokenResponses[keyof ValidateResetTokenResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/access/reset-password';
};

export type ResetPasswordErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Document created, URL follows
     */
    201: ResetPasswordResponse;
};

export type ResetPasswordResponse2 = ResetPasswordResponses[keyof ResetPasswordResponses];

export type AccountRegisterData = {
    body: AccountRegister;
    path?: never;
    query?: never;
    url: '/api/access/signup';
};

export type AccountRegisterErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AccountRegisterError = AccountRegisterErrors[keyof AccountRegisterErrors];

export type AccountRegisterResponses = {
    /**
     * Document created, URL follows
     */
    201: User;
};

export type AccountRegisterResponse = AccountRegisterResponses[keyof AccountRegisterResponses];

export type ApiEmailVerificationStatusUserIdGetVerificationStatusData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/email-verification/status/{user_id}';
};

export type ApiEmailVerificationStatusUserIdGetVerificationStatusErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEmailVerificationStatusUserIdGetVerificationStatusError = ApiEmailVerificationStatusUserIdGetVerificationStatusErrors[keyof ApiEmailVerificationStatusUserIdGetVerificationStatusErrors];

export type ApiEmailVerificationStatusUserIdGetVerificationStatusResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: boolean;
    };
};

export type ApiEmailVerificationStatusUserIdGetVerificationStatusResponse = ApiEmailVerificationStatusUserIdGetVerificationStatusResponses[keyof ApiEmailVerificationStatusUserIdGetVerificationStatusResponses];

export type ApiEmailVerificationRequestRequestVerificationData = {
    body: EmailVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/email-verification/request';
};

export type ApiEmailVerificationRequestRequestVerificationErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEmailVerificationRequestRequestVerificationError = ApiEmailVerificationRequestRequestVerificationErrors[keyof ApiEmailVerificationRequestRequestVerificationErrors];

export type ApiEmailVerificationRequestRequestVerificationResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: string;
    };
};

export type ApiEmailVerificationRequestRequestVerificationResponse = ApiEmailVerificationRequestRequestVerificationResponses[keyof ApiEmailVerificationRequestRequestVerificationResponses];

export type ApiEmailVerificationVerifyVerifyEmailData = {
    body: EmailVerificationConfirm;
    path?: never;
    query?: never;
    url: '/api/email-verification/verify';
};

export type ApiEmailVerificationVerifyVerifyEmailErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiEmailVerificationVerifyVerifyEmailError = ApiEmailVerificationVerifyVerifyEmailErrors[keyof ApiEmailVerificationVerifyVerifyEmailErrors];

export type ApiEmailVerificationVerifyVerifyEmailResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: User;
};

export type ApiEmailVerificationVerifyVerifyEmailResponse = ApiEmailVerificationVerifyVerifyEmailResponses[keyof ApiEmailVerificationVerifyVerifyEmailResponses];

export type ApiAuthOauthAccountsGetOauthAccountsData = {
    body?: never;
    path?: never;
    query: {
        oauth_account_service: unknown;
    };
    url: '/api/auth/oauth/accounts';
};

export type ApiAuthOauthAccountsGetOauthAccountsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiAuthOauthAccountsGetOauthAccountsError = ApiAuthOauthAccountsGetOauthAccountsErrors[keyof ApiAuthOauthAccountsGetOauthAccountsErrors];

export type ApiAuthOauthAccountsGetOauthAccountsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<OAuthAccountInfo>;
};

export type ApiAuthOauthAccountsGetOauthAccountsResponse = ApiAuthOauthAccountsGetOauthAccountsResponses[keyof ApiAuthOauthAccountsGetOauthAccountsResponses];

export type ApiAuthOauthGoogleGoogleAuthorizeData = {
    body?: never;
    path?: never;
    query: {
        settings: AppSettings;
        redirect_url?: string | null;
    };
    url: '/api/auth/oauth/google';
};

export type ApiAuthOauthGoogleGoogleAuthorizeErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiAuthOauthGoogleGoogleAuthorizeError = ApiAuthOauthGoogleGoogleAuthorizeErrors[keyof ApiAuthOauthGoogleGoogleAuthorizeErrors];

export type ApiAuthOauthGoogleGoogleAuthorizeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: OAuthAuthorizationResponse;
};

export type ApiAuthOauthGoogleGoogleAuthorizeResponse = ApiAuthOauthGoogleGoogleAuthorizeResponses[keyof ApiAuthOauthGoogleGoogleAuthorizeResponses];

export type ApiAuthOauthGoogleCallbackGoogleCallbackData = {
    body?: never;
    path?: never;
    query: {
        session: unknown;
        settings: AppSettings;
        user_service: unknown;
        oauth_account_service: unknown;
        code: string;
        state?: string | null;
        error?: string | null;
    };
    url: '/api/auth/oauth/google/callback';
};

export type ApiAuthOauthGoogleCallbackGoogleCallbackErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiAuthOauthGoogleCallbackGoogleCallbackError = ApiAuthOauthGoogleCallbackGoogleCallbackErrors[keyof ApiAuthOauthGoogleCallbackGoogleCallbackErrors];

export type ApiAuthOauthGoogleCallbackGoogleCallbackResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: unknown;
    };
};

export type ApiAuthOauthGoogleCallbackGoogleCallbackResponse = ApiAuthOauthGoogleCallbackGoogleCallbackResponses[keyof ApiAuthOauthGoogleCallbackGoogleCallbackResponses];

export type ApiAuthOauthLinkLinkOauthAccountData = {
    body: OAuthLinkRequest;
    path?: never;
    query: {
        settings: AppSettings;
        oauth_account_service: unknown;
    };
    url: '/api/auth/oauth/link';
};

export type ApiAuthOauthLinkLinkOauthAccountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiAuthOauthLinkLinkOauthAccountError = ApiAuthOauthLinkLinkOauthAccountErrors[keyof ApiAuthOauthLinkLinkOauthAccountErrors];

export type ApiAuthOauthLinkLinkOauthAccountResponses = {
    /**
     * Document created, URL follows
     */
    201: OAuthAccountInfo;
};

export type ApiAuthOauthLinkLinkOauthAccountResponse = ApiAuthOauthLinkLinkOauthAccountResponses[keyof ApiAuthOauthLinkLinkOauthAccountResponses];

export type ApiAuthOauthUnlinkUnlinkOauthAccountData = {
    body: OAuthLinkRequest;
    path?: never;
    query: {
        oauth_account_service: unknown;
    };
    url: '/api/auth/oauth/unlink';
};

export type ApiAuthOauthUnlinkUnlinkOauthAccountErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ApiAuthOauthUnlinkUnlinkOauthAccountError = ApiAuthOauthUnlinkUnlinkOauthAccountErrors[keyof ApiAuthOauthUnlinkUnlinkOauthAccountErrors];

export type ApiAuthOauthUnlinkUnlinkOauthAccountResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: unknown;
    };
};

export type ApiAuthOauthUnlinkUnlinkOauthAccountResponse = ApiAuthOauthUnlinkUnlinkOauthAccountResponses[keyof ApiAuthOauthUnlinkUnlinkOauthAccountResponses];

export type AccountProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type AccountProfileResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: User;
};

export type AccountProfileResponse = AccountProfileResponses[keyof AccountProfileResponses];

export type AccountProfileUpdateData = {
    body: ProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type AccountProfileUpdateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AccountProfileUpdateError = AccountProfileUpdateErrors[keyof AccountProfileUpdateErrors];

export type AccountProfileUpdateResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: User;
};

export type AccountProfileUpdateResponse = AccountProfileUpdateResponses[keyof AccountProfileUpdateResponses];

export type AccountDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type AccountDeleteResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type AccountDeleteResponse = AccountDeleteResponses[keyof AccountDeleteResponses];

export type AccountPasswordUpdateData = {
    body: PasswordUpdate;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type AccountPasswordUpdateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AccountPasswordUpdateError = AccountPasswordUpdateErrors[keyof AccountPasswordUpdateErrors];

export type AccountPasswordUpdateResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Message;
};

export type AccountPasswordUpdateResponse = AccountPasswordUpdateResponses[keyof AccountPasswordUpdateResponses];

export type DeleteRoleData = {
    body?: never;
    path: {
        /**
         * The role to delete.
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type DeleteRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type GetRoleData = {
    body?: never;
    path: {
        /**
         * The role to retrieve.
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type GetRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Role;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type UpdateRoleData = {
    body: RoleUpdate;
    path: {
        /**
         * The role to update.
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type UpdateRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Role;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type CreateRoleData = {
    body: RoleCreate;
    path: {
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type CreateRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors];

export type CreateRoleResponses = {
    /**
     * Document created, URL follows
     */
    201: Role;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string> | null;
        searchString?: string | null;
        searchIgnoreCase?: boolean | null;
        orderBy?: string | null;
        sortOrder?: 'asc' | 'desc' | null;
    };
    url: '/api/roles';
};

export type ListRolesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<Role>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string> | null;
        createdBefore?: string | null;
        createdAfter?: string | null;
        updatedBefore?: string | null;
        updatedAfter?: string | null;
        searchString?: string | null;
        searchIgnoreCase?: boolean | null;
        currentPage?: number;
        pageSize?: number;
        orderBy?: string | null;
        sortOrder?: 'asc' | 'desc' | null;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<User>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Document created, URL follows
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * The user to delete.
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * The user to retrieve.
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * The user to update.
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListTeamsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string> | null;
    };
    url: '/api/teams';
};

export type ListTeamsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ListTeamsError = ListTeamsErrors[keyof ListTeamsErrors];

export type ListTeamsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<Team>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ListTeamsResponse = ListTeamsResponses[keyof ListTeamsResponses];

export type CreateTeamData = {
    body: TeamCreate;
    path?: never;
    query?: never;
    url: '/api/teams';
};

export type CreateTeamErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type CreateTeamError = CreateTeamErrors[keyof CreateTeamErrors];

export type CreateTeamResponses = {
    /**
     * Document created, URL follows
     */
    201: Team;
};

export type CreateTeamResponse = CreateTeamResponses[keyof CreateTeamResponses];

export type DeleteTeamData = {
    body?: never;
    path: {
        /**
         * The team to delete.
         */
        team_id: string;
    };
    query?: never;
    url: '/api/teams/{team_id}';
};

export type DeleteTeamErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type DeleteTeamError = DeleteTeamErrors[keyof DeleteTeamErrors];

export type DeleteTeamResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type DeleteTeamResponse = DeleteTeamResponses[keyof DeleteTeamResponses];

export type GetTeamData = {
    body?: never;
    path: {
        /**
         * The team to retrieve.
         */
        team_id: string;
    };
    query?: never;
    url: '/api/teams/{team_id}';
};

export type GetTeamErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type GetTeamError = GetTeamErrors[keyof GetTeamErrors];

export type GetTeamResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Team;
};

export type GetTeamResponse = GetTeamResponses[keyof GetTeamResponses];

export type UpdateTeamData = {
    body: TeamUpdate;
    path: {
        /**
         * The team to update.
         */
        team_id: string;
    };
    query?: never;
    url: '/api/teams/{team_id}';
};

export type UpdateTeamErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type UpdateTeamError = UpdateTeamErrors[keyof UpdateTeamErrors];

export type UpdateTeamResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Team;
};

export type UpdateTeamResponse = UpdateTeamResponses[keyof UpdateTeamResponses];

export type DeleteTeamInvitationData = {
    body?: never;
    path: {
        team_id: string;
        invitation_id: string;
    };
    query?: never;
    url: '/{team_id}/{invitation_id}';
};

export type DeleteTeamInvitationErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type DeleteTeamInvitationError = DeleteTeamInvitationErrors[keyof DeleteTeamInvitationErrors];

export type DeleteTeamInvitationResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type DeleteTeamInvitationResponse = DeleteTeamInvitationResponses[keyof DeleteTeamInvitationResponses];

export type AcceptTeamInvitationData = {
    body?: never;
    path: {
        team_id: string;
        invitation_id: string;
    };
    query?: never;
    url: '/{team_id}/{invitation_id}';
};

export type AcceptTeamInvitationErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AcceptTeamInvitationError = AcceptTeamInvitationErrors[keyof AcceptTeamInvitationErrors];

export type AcceptTeamInvitationResponses = {
    /**
     * Document created, URL follows
     */
    201: Message;
};

export type AcceptTeamInvitationResponse = AcceptTeamInvitationResponses[keyof AcceptTeamInvitationResponses];

export type ListTeamInvitationsData = {
    body?: never;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/{team_id}';
};

export type ListTeamInvitationsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ListTeamInvitationsError = ListTeamInvitationsErrors[keyof ListTeamInvitationsErrors];

export type ListTeamInvitationsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<TeamInvitation>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ListTeamInvitationsResponse = ListTeamInvitationsResponses[keyof ListTeamInvitationsResponses];

export type CreateTeamInvitationData = {
    body: TeamInvitationCreate;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/{team_id}';
};

export type CreateTeamInvitationErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type CreateTeamInvitationError = CreateTeamInvitationErrors[keyof CreateTeamInvitationErrors];

export type CreateTeamInvitationResponses = {
    /**
     * Document created, URL follows
     */
    201: TeamInvitation;
};

export type CreateTeamInvitationResponse = CreateTeamInvitationResponses[keyof CreateTeamInvitationResponses];

export type RevokeUserRoleData = {
    body: UserRoleRevoke;
    path?: never;
    query: {
        /**
         * The role to revoke.
         */
        role_slug: string;
    };
    url: '/api/users/roles';
};

export type RevokeUserRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type RevokeUserRoleError = RevokeUserRoleErrors[keyof RevokeUserRoleErrors];

export type RevokeUserRoleResponses = {
    /**
     * Request accepted, processing continues off-line
     */
    202: Message;
};

export type RevokeUserRoleResponse = RevokeUserRoleResponses[keyof RevokeUserRoleResponses];

export type AssignUserRoleData = {
    body: UserRoleAdd;
    path?: never;
    query: {
        /**
         * The role to grant.
         */
        role_slug: string;
    };
    url: '/api/users/roles';
};

export type AssignUserRoleErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AssignUserRoleError = AssignUserRoleErrors[keyof AssignUserRoleErrors];

export type AssignUserRoleResponses = {
    /**
     * Document created, URL follows
     */
    201: Message;
};

export type AssignUserRoleResponse = AssignUserRoleResponses[keyof AssignUserRoleResponses];

export type RemoveMemberFromTeamData = {
    body: TeamMemberModify;
    path: {
        /**
         * The team to delete.
         */
        team_id: string;
    };
    query?: never;
    url: '/api/teams/{team_id}/members';
};

export type RemoveMemberFromTeamErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type RemoveMemberFromTeamError = RemoveMemberFromTeamErrors[keyof RemoveMemberFromTeamErrors];

export type RemoveMemberFromTeamResponses = {
    /**
     * Request accepted, processing continues off-line
     */
    202: Team;
};

export type RemoveMemberFromTeamResponse = RemoveMemberFromTeamResponses[keyof RemoveMemberFromTeamResponses];

export type AddMemberToTeamData = {
    body: TeamMemberModify;
    path: {
        /**
         * The team to update.
         */
        team_id: string;
    };
    query?: never;
    url: '/api/teams/{team_id}/members';
};

export type AddMemberToTeamErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type AddMemberToTeamError = AddMemberToTeamErrors[keyof AddMemberToTeamErrors];

export type AddMemberToTeamResponses = {
    /**
     * Document created, URL follows
     */
    201: Team;
};

export type AddMemberToTeamResponse = AddMemberToTeamResponses[keyof AddMemberToTeamResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        /**
         * The tag to delete.
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}';
};

export type DeleteTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagData = {
    body?: never;
    path: {
        /**
         * The tag to retrieve.
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}';
};

export type GetTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type GetTagError = GetTagErrors[keyof GetTagErrors];

export type GetTagResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Tag;
};

export type GetTagResponse = GetTagResponses[keyof GetTagResponses];

export type UpdateTagData = {
    body: TagUpdate;
    path: {
        /**
         * The tag to update.
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}';
};

export type UpdateTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Tag;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type CreateTagData = {
    body: TagCreate;
    path: {
        tag_id: string;
    };
    query?: never;
    url: '/api/tags/{tag_id}';
};

export type CreateTagErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type CreateTagError = CreateTagErrors[keyof CreateTagErrors];

export type CreateTagResponses = {
    /**
     * Document created, URL follows
     */
    201: Tag;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type ListTagsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string> | null;
        createdBefore?: string | null;
        createdAfter?: string | null;
        updatedBefore?: string | null;
        updatedAfter?: string | null;
        searchString?: string | null;
        searchIgnoreCase?: boolean | null;
        orderBy?: string | null;
        sortOrder?: 'asc' | 'desc' | null;
    };
    url: '/api/tags';
};

export type ListTagsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ListTagsError = ListTagsErrors[keyof ListTagsErrors];

export type ListTagsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        items?: Array<Tag>;
        /**
         * Maximal number of items to send.
         */
        limit?: number;
        /**
         * Offset from the beginning of the query.
         */
        offset?: number;
        /**
         * Total number of items.
         */
        total?: number;
    };
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};
