services:
  cache:
    image: valkey/valkey:latest
    ports:
      - "16379:6379"
    hostname: cache
    command: redis-server --appendonly yes
    volumes:
      - cache-data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30
  db:
    image: postgres:latest
    ports:
      - "15432:5432"
    hostname: db
    environment:
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
      POSTGRES_DB: "app"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - app
      interval: 2s
      timeout: 3s
      retries: 40
  app:
    build:
      context: .
      dockerfile: deploy/docker/run/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      VITE_USE_SERVER_LIFESPAN: "false" # true if ssr or separate service
      SAQ_USE_SERVER_LIFESPAN: "false"
    env_file:
      - .env.docker.example
  worker:
    build:
      context: .
      dockerfile: deploy/docker/run/Dockerfile
    command: litestar workers run
    restart: always
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env.docker.example
  migrator:
    build:
      context: .
      dockerfile: deploy/docker/run/Dockerfile
    restart: "no"
    command: litestar database upgrade --no-prompt
    env_file:
      - .env.docker.example
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
volumes:
  db-data: {}
  cache-data: {}
