WORKER_ROOT = "/worker"
WORKER_QUEUE_ROOT = "/queues/{queue_id:uuid}"
WORKER_JOB_ROOT = "/queues/{queue_id:uuid}/jobs/{job_id:uuid}"
WORKER_QUEUE_LIST = "/api/queues/"
WORKER_QUEUE_DETAIL = "/api/queues/{queue_id:uuid}/"
WORKER_JOB_DETAIL = "/api/queues/{queue_id:uuid}/jobs/{job_id:uuid}"
WORKER_JOB_RETRY = "/api/queues/{queue_id:uuid}/jobs/{job_id:uuid}/retry"
WORKER_JOB_ABORT = "/api/queues/{queue_id:uuid}/jobs/{job_id:uuid}/abort"
